# Generated by Django 3.1.4 on 2020-12-20 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
