# Generated by Django 3.1.4 on 2021-02-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0003_auto_20210130_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
