# Generated by Django 3.1.4 on 2021-02-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0004_auto_20210209_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentation',
            name='doc_type',
            field=models.CharField(choices=[('HTML', 'html'), ('WRITTEN', 'written')], default=1, max_length=7),
        ),
    ]
