# Generated by Django 3.1.1 on 2020-12-23 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companynews', '0002_article_imgattach'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='imgAttach',
            new_name='image',
        ),
    ]
