# Generated by Django 3.1.1 on 2020-12-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companynews', '0003_auto_20201223_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='companynews/static/images/userUploads'),
        ),
    ]
