# Generated by Django 3.1.1 on 2020-12-28 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companynews', '0004_auto_20201228_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
    ]
